version: '3.3'
secrets:
  postgres_password:
      file: ./secrets/postgres_password
services:
  server:
    build: .
    ports:
      - "5000:8080"
    environment:
      PGPASSWORD: /run/secrets/postgres_password
    secrets:
      - postgres_password
  redis:
    image: "redis:alpine"
  postgres: 
    image: "postgres"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password