version: '3.3'
secrets:
  postgres_password:
      file: ./secrets/postgres_password
services:
  redis:
    image: "redis:alpine"
  postgres: 
    image: "postgres"
    environment:
      POSTGRES_DB: coup
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
  server:
    build: ./hatchery-service
    ports:
      - "5000:8080"
    environment:
      PGUSER: farmer
      PGDBNAME: coup
      PGPW_LOCATION: /run/secrets/postgres_password
    depends_on:
      - postgres
    secrets:
      - postgres_password