version: '3.3'
secrets:
  postgres_password:
      file: ./secrets/postgres_password
  session_authentication_key:
      file: ./secrets/session_authentication_key
  session_encryption_key:
      file: ./secrets/session_encryption_key
volumes:
  node_modules:
services:
  redis:
    image: "redis:alpine"
  postgres-hatchery: 
    image: "postgres"
    environment:
      POSTGRES_DB: coup
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
  hatchery:
    build: ./hatchery-service
    ports:
      - "5000:8080"
    environment:
      PGUSER: farmer
      PGDBNAME: coup
      PGPW_LOCATION: /run/secrets/postgres_password
      PGHOST: postgres-hatchery
    depends_on:
      - postgres-hatchery
    secrets:
      - postgres_password
  user:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "5050:8080"
    environment:
      PGUSER: farmer
      PGDBNAME: coup
      PGPW_LOCATION: /run/secrets/postgres_password
      PGHOST: postgres-user
    depends_on:
      - postgres-user
    secrets:
      - postgres_password
  postgres-user: 
    image: "postgres"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5482:5432"
    secrets:
      - postgres_password
  app:
    build: ./app-service
    environment:
      PUBLIC_PORT: 5100
      SESSION_AUTH_LOCATION: /run/secrets/session_authentication_key
      SESSION_CRYPT_LOCATION: /run/secrets/session_encryption_key
    ports:
      - "5100:8080"
    volumes:
      - "./hatch-react-app:/go/src/hatch/app-service/hatch"
    secrets:
      - session_authentication_key
      - session_encryption_key
  react-app:
    build:
      context: ./hatch-react-app
      dockerfile: Dockerfile
    volumes:
      - "./hatch-react-app:/hatch"
      - node_modules:/hatch/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true