version: '3.3'
secrets:
  postgres_password:
      file: ./secrets/postgres_password
services:
  redis:
    image: "redis:alpine"
  postgres-hatchery: 
    image: "postgres"
    environment:
      POSTGRES_DB: coup
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
  hatchery:
    build: ./hatchery-service
    ports:
      - "5000:8080"
    environment:
      PGUSER: farmer
      PGDBNAME: coup
      PGPW_LOCATION: /run/secrets/postgres_password
      PGHOST: postgres-hatchery
    depends_on:
      - postgres-hatchery
    secrets:
      - postgres_password
  user:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "5050:8080"
    environment:
      PGUSER: farmer
      PGDBNAME: user
      PGPW_LOCATION: /run/secrets/postgres_password
      PGHOST: postgres-user
    depends_on:
      - postgres-user
    secrets:
      - postgres_password
  postgres-user: 
    image: "postgres"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: farmer
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5482:5432"
    secrets:
      - postgres_password
  app:
    build: ./app-service
    ports:
      - "5100:8080"
    volumes:
      - "./hatch-react-app:/go/src/app-service/hatch"
  react-app:
    build:
      context: ./hatch-react-app
      dockerfile: Dockerfile
    volumes:
      - "./hatch-react-app:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true