// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User is a user of hatch
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_65f581328c4e7c5c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// User is a user of hatch
type NewUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_65f581328c4e7c5c, []int{1}
}
func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (dst *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(dst, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// UserId is the Id by which users are stored
type UserId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_65f581328c4e7c5c, []int{2}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Status returns either 'success' or 'error'
type Status struct {
	Status               string   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_65f581328c4e7c5c, []int{3}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "hatch.rpc.User")
	proto.RegisterType((*NewUser)(nil), "hatch.rpc.NewUser")
	proto.RegisterType((*UserId)(nil), "hatch.rpc.UserId")
	proto.RegisterType((*Status)(nil), "hatch.rpc.Status")
}

func init() { proto.RegisterFile("rpc/user/user.proto", fileDescriptor_user_65f581328c4e7c5c) }

var fileDescriptor_user_65f581328c4e7c5c = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0xc6, 0x69, 0xac, 0x79, 0xbc, 0x53, 0x14, 0x4f, 0x91, 0xf0, 0xa6, 0xd2, 0xc9, 0xc5, 0x08,
	0x16, 0x77, 0x71, 0x11, 0x17, 0x87, 0x16, 0x17, 0xb7, 0x98, 0x1e, 0x36, 0x60, 0x6d, 0x49, 0x52,
	0xfd, 0xf7, 0xa5, 0xd7, 0x52, 0x4a, 0x71, 0x09, 0xf7, 0x7d, 0xc9, 0xef, 0xbb, 0xdc, 0xc1, 0xa5,
	0xef, 0xed, 0xdd, 0x10, 0xc8, 0xf3, 0xa1, 0x7b, 0xdf, 0xc5, 0x0e, 0xf7, 0x8d, 0x89, 0xb6, 0xd1,
	0xbe, 0xb7, 0xf9, 0x23, 0xa4, 0x6f, 0x81, 0x3c, 0x9e, 0x81, 0x70, 0xb5, 0x4a, 0xb2, 0xe4, 0x66,
	0x5f, 0x0a, 0x57, 0xe3, 0x15, 0x1c, 0x53, 0x6b, 0xdc, 0x97, 0x12, 0x6c, 0x4d, 0x02, 0x11, 0xd2,
	0x6f, 0xd3, 0x92, 0x3a, 0x62, 0x93, 0xeb, 0xbc, 0x80, 0xdd, 0x2b, 0xfd, 0x72, 0xc8, 0x02, 0x25,
	0xff, 0x41, 0x62, 0x05, 0x29, 0x90, 0x23, 0xf1, 0x52, 0x6f, 0x1b, 0xe7, 0x19, 0xc8, 0x2a, 0x9a,
	0x38, 0x04, 0xbc, 0x06, 0x19, 0xb8, 0x9a, 0x6f, 0x67, 0x75, 0x1f, 0xe0, 0x64, 0x64, 0x2b, 0xf2,
	0x3f, 0xce, 0x12, 0xde, 0xc2, 0xee, 0x99, 0x22, 0xf7, 0xbf, 0xd0, 0xcb, 0x60, 0x7a, 0x8a, 0x3f,
	0x9c, 0x6f, 0x2c, 0x7c, 0x80, 0xd3, 0x92, 0x3e, 0x5d, 0x88, 0xe4, 0x59, 0xe3, 0xea, 0xc1, 0x3c,
	0xc7, 0x61, 0x9d, 0x33, 0x7d, 0xe6, 0x49, 0xbe, 0xa7, 0xe3, 0x02, 0x3f, 0x24, 0x6f, 0xb0, 0xf8,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x14, 0xd3, 0x1d, 0x0e, 0x58, 0x01, 0x00, 0x00,
}
