// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/user/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User is a user of hatch
type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_aeefc210a1bd2d9c, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// User is a user of hatch
type NewUser struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_aeefc210a1bd2d9c, []int{1}
}
func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (dst *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(dst, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// UserId is the Id by which users are stored
type UserId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_aeefc210a1bd2d9c, []int{2}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Status returns either 'success' or 'error'
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_aeefc210a1bd2d9c, []int{3}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "hatch.rpc.User")
	proto.RegisterType((*NewUser)(nil), "hatch.rpc.NewUser")
	proto.RegisterType((*UserId)(nil), "hatch.rpc.UserId")
	proto.RegisterType((*Status)(nil), "hatch.rpc.Status")
}

func init() { proto.RegisterFile("rpc/user/user.proto", fileDescriptor_user_aeefc210a1bd2d9c) }

var fileDescriptor_user_aeefc210a1bd2d9c = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xec, 0xa6, 0xec, 0x28, 0x8a, 0xa3, 0x87, 0xb0, 0x27, 0xe9, 0xc9, 0x8b, 0x11,
	0x5c, 0xf4, 0x2c, 0x5e, 0xc4, 0x8b, 0x87, 0x2e, 0x5e, 0xbc, 0xc5, 0x64, 0xd8, 0x0d, 0x58, 0x5b,
	0x92, 0xac, 0x7e, 0x7d, 0xc9, 0xd4, 0x2d, 0xa5, 0x78, 0x29, 0xf3, 0x5e, 0xf3, 0x7b, 0xf3, 0x07,
	0x2e, 0x42, 0x6f, 0x6f, 0xf7, 0x91, 0x02, 0x7f, 0x74, 0x1f, 0xba, 0xd4, 0xe1, 0x72, 0x67, 0x92,
	0xdd, 0xe9, 0xd0, 0xdb, 0xfa, 0x11, 0xca, 0xb7, 0x48, 0x01, 0x4f, 0x41, 0x78, 0xa7, 0x8a, 0xab,
	0xe2, 0x7a, 0xd9, 0x08, 0xef, 0xf0, 0x12, 0x16, 0xd4, 0x1a, 0xff, 0xa9, 0x04, 0x5b, 0x83, 0x40,
	0x84, 0xf2, 0xcb, 0xb4, 0xa4, 0x8e, 0xd8, 0xe4, 0xba, 0x5e, 0x43, 0xf5, 0x4a, 0x3f, 0x1c, 0x32,
	0x42, 0xc5, 0x7f, 0x90, 0x98, 0x40, 0x0a, 0x64, 0x26, 0x5e, 0xdc, 0xbc, 0x71, 0xfd, 0x00, 0x72,
	0x93, 0x4c, 0xda, 0xc7, 0xcc, 0xd9, 0xce, 0x11, 0xff, 0x5b, 0x34, 0x5c, 0xa3, 0x82, 0xaa, 0xa5,
	0x18, 0xcd, 0xf6, 0x10, 0x77, 0x90, 0x77, 0x11, 0x8e, 0x73, 0xe2, 0x86, 0xc2, 0xb7, 0xb7, 0x84,
	0x37, 0x50, 0x3d, 0x53, 0xe2, 0xa9, 0xce, 0xf5, 0xb8, 0xae, 0x1e, 0x9a, 0xae, 0xce, 0x66, 0x16,
	0xde, 0xc3, 0x49, 0x43, 0x5b, 0x1f, 0x13, 0x05, 0xd6, 0x38, 0x79, 0xf0, 0xb7, 0xdd, 0x6a, 0x9a,
	0x33, 0x8c, 0xf8, 0x24, 0xdf, 0xcb, 0x7c, 0xd6, 0x0f, 0xc9, 0x77, 0x5d, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x35, 0x1d, 0xbc, 0xaa, 0x6e, 0x01, 0x00, 0x00,
}
